# Generated by Django 4.0.6 on 2022-08-07 10:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
